# docker-compose.yml
services:
  pgdatabase:
    image: postgres:16.1-bullseye
    env_file:
      - database.env
    volumes:
      - "./ny_taxi_pg_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"